---
docker_registry_container: andrewrothstein/distribution:s3-v2-presign
docker_registry_http_secret: 9009adbe-e838-11e6-a9c8-036d130d0626
docker_registry_storage_s3_access_key: a8ffd786-e81e-11e6-99b5-0ba0466abd4f
docker_registry_storage_s3_secret_key: e06996b2-e81e-11e6-bb28-1b752defb207
docker_registry_pki_dir: '{{playbook_dir}}/pki-dir'
