---
- hosts: all
  become: True
  become_user: root
  roles:
    - andrewrothstein.proxify
    - andrewrothstein.sudoers
    - andrewrothstein.epel
    - andrewrothstein.curl
    - andrewrothstein.nettools
    - andrewrothstein.unarchive-deps
    - andrewrothstein.ntp
    - andrewrothstein.ssl-key
    - andrewrothstein.docker
    - andrewrothstein.docker-py
    - andrewrothstein.ssh-reconnect
  tasks:
    - name: add the vagrant user to the docker group
      user: name=vagrant groups=docker append=yes
      register: vagrant_added_to_docker_group
    - name: ssh reconnect
      when: vagrant_added_to_docker_group | changed
      ssh-reconnect:
