---
- hosts: all
  become: True
  become_user: root
  roles:
    - andrewrothstein.proxify
    - andrewrothstein.sudoers
    - andrewrothstein.epel
    - andrewrothstein.ntp
    - andrewrothstein.ssl-key
    - andrewrothstein.nettools
    - andrewrothstein.docker
    - andrewrothstein.docker-py
  tasks:
    - name: add the vagrant user to the docker group
      user: name=vagrant groups=docker
