---
- src: andrewrothstein.sudoers
- src: andrewrothstein.epel
- src: andrewrothstein.ntp
- src: andrewrothstein.influxdb
- src: andrewrothstein.etcd
- src: andrewrothstein.elasticsearch
- src: andrewrothstein.ntp
- src: andrewrothstein.docker
- src: andrewrothstein.consul
