---
- src: andrewrothstein.ssl-key
  version: v2.0.0
- src: andrewrothstein.kafka
  version: v2.0.1
- src: andrewrothstein.kafka-broker
- src: andrewrothstein.kafka-producer
- src: andrewrothstein.kafka-consumer

