---
- src: andrewrothstein.sudoers
- src: andrewrothstein.epel
- src: andrewrothstein.ntp
- src: andrewrothstein.ssl-key
- src: andrewrothstein.etcd
  version: 'v1.0.4'
- src: andrewrothstein.consul
  version: 'v1.0.7'
- src: andrewrothstein.docker
  version: 'v3.0.2'
- src: andrewrothstein.docker-py
  version: 'v1.0.1'
- src: andrewrothstein.docker-swarm
  version: 'v2.0.0'
- src: andrewrothstein.mesosphere-mesos
  version: 'v1.0.0'
- src: andrewrothstein.mesosphere-zookeeper
  version: 'v1.0.0'
- src: andrewrothstein.mesosphere-mesosmaster
  version: 'v1.0.0'
- src: andrewrothstein.mesosphere-mesosslave
  version: 'v1.0.0'
- src: andrewrothstein.mesosphere-marathon
  version: 'v1.0.0'
- src: andrewrothstein.mesosphere-chronos
  version: 'v1.0.0'