---
- src: andrewrothstein.ssl-key
  version: v2.0.0
- src: andrewrothstein.consul
  version: v2.0.0
- src: andrewrothstein.docker
  version: v4.0.3
- src: andrewrothstein.cassandra
  version: v1.0.1
- src: andrewrothstein.pithos
  version: v1.0.0
- src: andrewrothstein.docker-registry
  version: v2.0.0
