---
- src: andrewrothstein.sudoers
- src: andrewrothstein.epel
- src: andrewrothstein.ntp
- src: andrewrothstein.ssl-key
- src: andrewrothstein.etcd
- src: andrewrothstein.consul
- src: andrewrothstein.docker
- src: andrewrothstein.docker-py
- src: andrewrothstein.docker-swarm
- src: andrewrothstein.ignite
