---
- src: andrewrothstein.ssl-key
  version: v2.0.1
- src: andrewrothstein.consul-cluster
  version: v1.0.9
- src: andrewrothstein.docker
  version: v4.3.0
- src: andrewrothstein.orientdb
  version: v2.0.0
