---
- src: andrewrothstein.pki
  version: v1.0.4
- src: andrewrothstein.etcd-cluster
  version: v1.0.5
- src: andrewrothstein.consul-cluster
  version: v1.0.11
- src: andrewrothstein.docker
  version: v5.0.1
