---
- src: andrewrothstein.pki
  version: v1.0.4
- src: andrewrothstein.docker
  version: v5.0.1
- src: andrewrothstein.consul-cluster
  version: v1.0.11
- src: andrewrothstein.etcd-cluster
  version: v1.0.3
- src: andrewrothstein.kubernetes-cluster
  version: v1.0.0
